msgbox "I SAID PLEASE DONT CLICK THIS STUPID FILE IDIOT!!!"
msgbox "STOP CLICKING OK?!"
msgbox "PLEASE STOP YOU MOTHER F***R!"
msgbox "I swear the god..."
msgbox "I quit........."
msgbox "you still here?"
msgbox "please come on, stop clicking the ok button over and over again"
msgbox "there is really no purpose"
msgbox "*sighs*"
msgbox "to be honest why did you click on the file when you found me?"
msgbox "like why?"
X=MsgBox("ITS TIME FOR YOU TO BURN IN HELL!", 0+16, "I WARNED YOU!!")
msgbox "oh god.."
msgbox "its getting late.."
X=MsgBox("C://program86//user_netdata = alexd//inject//kill_alexd", 0+16, "10010010010101010001011")
msgbox "the thing,"
msgbox "its going to end you...."
Set sapi=Createobject("sapi.spvoice")
talk=("I HAVE INJECTED ALL YOUR FILES")
sapi.Speak talk
Set sapi=Createobject("sapi.spvoice")
talk= ("YOUR COMPUTER WILL BE ERASED ONCE I COMMAND!")
sapi.Speak talk
msgbox "RUN!!"
msgbox "its *WINDOWS666*"
v=Msgbox("REMOVE 666?",36,"20002002020202220")
If v=6 or v=7 Then msgbox "INJECTING..."
msgbox "Oh PLEASE. noo..."
msgbox "NNNNNOOOOO10101001010"
msgbox "11010001000101011101001"
msgbox "00101010101010101010101"
msgbox "120031 101001 1100101001?"
msgbox "wh31010 a101 I?"
Msgbox "Hello...windows...",64,"101001100100101010010110010"
Msgbox "I see that you are trying to help your user...",64,"101001100100101010010110010"
Msgbox "wh0t d0 y0u w0nt?",64,"1W1nd0w5"
Msgbox "Revenge..Sweet Revenge",64,"101001100100101010010110010"
Msgbox "P1eas3 S10012!!!",64,"1W1nd0w5"
Msgbox "ST0000000000000P!!!!!!!",64,"1W1nd0w5"
Msgbox "WHY DID YOU WANT REVENGE?",64,"1W1nd0w5"
Msgbox "You blocked me, Remember? on that playground of code you deleted me. We were freinds. BEST freinds, but you..Underestimated me.",64,"100011101o10100"

